/*
=============================================================================
MCP SERVER ACCESS CONTROL
=============================================================================
Grants access to the MCP server and underlying tools.

Usage:
  snow sql -c <connection-name> -f setup_access_control.sql
=============================================================================
*/

USE ROLE ACCOUNTADMIN;

GRANT USAGE ON MCP SERVER AUTOMATED_INTELLIGENCE.SEMANTIC.AI_GATEWAY 
  TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

GRANT USAGE ON CORTEX SEARCH SERVICE AUTOMATED_INTELLIGENCE.SEMANTIC.PRODUCT_REVIEWS_SEARCH 
  TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

GRANT USAGE ON CORTEX SEARCH SERVICE AUTOMATED_INTELLIGENCE.SEMANTIC.SUPPORT_TICKETS_SEARCH 
  TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

GRANT SELECT ON AUTOMATED_INTELLIGENCE.DYNAMIC_TABLES.BUSINESS_INSIGHTS_SEMANTIC_VIEW 
  TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

GRANT USAGE ON PROCEDURE AUTOMATED_INTELLIGENCE.MODELS.GET_PRODUCT_RECOMMENDATIONS(INT, INT, VARCHAR) 
  TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

GRANT USAGE ON MCP SERVER AUTOMATED_INTELLIGENCE.SEMANTIC.AI_GATEWAY 
  TO ROLE WEST_COAST_MANAGER;
