-- ============================================================================
-- Cleanup Script - West Coast Manager Role
-- ============================================================================

USE DATABASE AUTOMATED_INTELLIGENCE;
USE SCHEMA RAW;

-- Remove row access policy from customers table
ALTER TABLE AUTOMATED_INTELLIGENCE.RAW.CUSTOMERS 
    DROP ROW ACCESS POLICY customers_region_policy;

-- Drop the row access policy
DROP ROW ACCESS POLICY IF EXISTS customers_region_policy;

-- Revoke agent access
REVOKE USAGE ON AGENT snowflake_intelligence.agents.business_insights_agent FROM ROLE west_coast_manager;
REVOKE USAGE ON SCHEMA snowflake_intelligence.agents FROM ROLE west_coast_manager;
REVOKE USAGE ON DATABASE snowflake_intelligence FROM ROLE west_coast_manager;

-- Revoke table access
REVOKE SELECT ON AUTOMATED_INTELLIGENCE.DYNAMIC_TABLES.BUSINESS_INSIGHTS_SEMANTIC_VIEW FROM ROLE west_coast_manager;
REVOKE SELECT ON AUTOMATED_INTELLIGENCE.DYNAMIC_TABLES.ENRICHED_ORDER_ITEMS FROM ROLE west_coast_manager;
REVOKE SELECT ON AUTOMATED_INTELLIGENCE.DYNAMIC_TABLES.ENRICHED_ORDERS FROM ROLE west_coast_manager;
REVOKE SELECT ON AUTOMATED_INTELLIGENCE.DYNAMIC_TABLES.DAILY_BUSINESS_METRICS FROM ROLE west_coast_manager;

REVOKE SELECT ON TABLE AUTOMATED_INTELLIGENCE.RAW.SUPPORT_TICKETS FROM ROLE west_coast_manager;
REVOKE SELECT ON TABLE AUTOMATED_INTELLIGENCE.RAW.PRODUCT_REVIEWS FROM ROLE west_coast_manager;
REVOKE SELECT ON TABLE AUTOMATED_INTELLIGENCE.RAW.PRODUCT_CATALOG FROM ROLE west_coast_manager;
REVOKE SELECT ON TABLE AUTOMATED_INTELLIGENCE.RAW.ORDER_ITEMS FROM ROLE west_coast_manager;
REVOKE SELECT ON TABLE AUTOMATED_INTELLIGENCE.RAW.ORDERS FROM ROLE west_coast_manager;
REVOKE SELECT ON TABLE AUTOMATED_INTELLIGENCE.RAW.CUSTOMERS FROM ROLE west_coast_manager;

-- Revoke schema and warehouse access
REVOKE USAGE ON SCHEMA AUTOMATED_INTELLIGENCE.DYNAMIC_TABLES FROM ROLE west_coast_manager;
REVOKE USAGE ON SCHEMA AUTOMATED_INTELLIGENCE.RAW FROM ROLE west_coast_manager;
REVOKE USAGE ON DATABASE AUTOMATED_INTELLIGENCE FROM ROLE west_coast_manager;
REVOKE USAGE ON WAREHOUSE AUTOMATED_INTELLIGENCE_WH FROM ROLE west_coast_manager;

-- Drop the role
DROP ROLE IF EXISTS west_coast_manager;

-- Verify cleanup
SHOW ROW ACCESS POLICIES IN SCHEMA AUTOMATED_INTELLIGENCE.RAW;
SHOW ROLES LIKE 'WEST_COAST_MANAGER';
