create extension if not exists pg_lake_spatial cascade;

-- Foreign tables for Snowflake Iceberg data
-- These point to Iceberg metadata files (NOT raw parquet) to preserve Iceberg semantics
-- Auto-generated by setup.sh at Mon Jan 26 18:41:55 PST 2026

DROP FOREIGN TABLE IF EXISTS product_reviews;
CREATE FOREIGN TABLE product_reviews()
SERVER pg_lake
OPTIONS (path 's3://dash-iceberg-snowflake/demos/demos/pg_lake/product_reviews.I4eDpa3p/metadata/00002-0b84dad7-1ae1-4431-9cce-a9081920d4c7.metadata.json');

DROP FOREIGN TABLE IF EXISTS support_tickets;
CREATE FOREIGN TABLE support_tickets()
SERVER pg_lake
OPTIONS (path 's3://dash-iceberg-snowflake/demos/demos/pg_lake/support_tickets.qZPKfN5O/metadata/00002-94710b37-0927-4c44-9b33-392f5dcd05f7.metadata.json');
