-- Recreate Snowpipe Streaming pipes to match UUID schema

USE ROLE snowflake_intelligence_admin;
USE DATABASE automated_intelligence;
USE SCHEMA raw;

-- Drop existing pipes
DROP PIPE IF EXISTS ORDERS_PIPE;
DROP PIPE IF EXISTS ORDER_ITEMS_PIPE;

-- Recreate ORDERS_PIPE with VARCHAR(36) for order_id (UUID)
CREATE OR REPLACE PIPE ORDERS_PIPE
AS
COPY INTO ORDERS
FROM (
    SELECT
        $1:ORDER_ID::VARCHAR(36),
        $1:CUSTOMER_ID::INT,
        $1:ORDER_DATE::TIMESTAMP,
        $1:ORDER_STATUS::VARCHAR(20),
        $1:TOTAL_AMOUNT::DECIMAL(10,2),
        $1:DISCOUNT_PERCENT::DECIMAL(5,2),
        $1:SHIPPING_COST::DECIMAL(8,2)
    FROM TABLE(DATA_SOURCE(TYPE => 'STREAMING'))
);

-- Recreate ORDER_ITEMS_PIPE with VARCHAR(36) for IDs (UUIDs)
CREATE OR REPLACE PIPE ORDER_ITEMS_PIPE
AS
COPY INTO ORDER_ITEMS
FROM (
    SELECT
        $1:ORDER_ITEM_ID::VARCHAR(36),
        $1:ORDER_ID::VARCHAR(36),
        $1:PRODUCT_ID::INT,
        $1:PRODUCT_NAME::VARCHAR(100),
        $1:PRODUCT_CATEGORY::VARCHAR(50),
        $1:QUANTITY::INT,
        $1:UNIT_PRICE::DECIMAL(10,2),
        $1:LINE_TOTAL::DECIMAL(12,2)
    FROM TABLE(DATA_SOURCE(TYPE => 'STREAMING'))
);

-- Verify pipes
SHOW PIPES;
